// Faça um programa que receba 3 números inteiros, e deve imprimir, qual é o maior, qual é o menor.

let number1 = 15;
let number2 = 10;
let number3 = 5;

if (number1 > number2, number1 > number3) {
    console.log(" O maior e 15")
    
} 
else if (number2 > number1, number2 > number3) {
    console.log(" O maior e 10")

}
else if (number3 > number1, number3 > number2) {
console.log(" O maior e 5")
}